<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:macro name="erp42_racing_model" params="">

        <!-- ======================================== Variables ======================================== -->

        <!-- Arguments -->
        <xacro:arg name="robot_namespace" default="/" />
        <xacro:include filename="$(find erp42_racing_description)/urdf/erp42_racing_front_wheel.xacro" />
        <xacro:include filename="$(find erp42_racing_description)/urdf/erp42_racing_rear_wheel.xacro" />

        <!-- Constants -->
        <xacro:property name="PI" value="3.14159"/>

        <!-- Front wheel geometry (from (170/560R14) -->
        <xacro:property name="front_wheel_length" value="0.170" />
        <xacro:property name="front_wheel_radius" value="0.280" />

        <!-- Rear wheel geometry (from 200/580R15) -->
        <xacro:property name="rear_wheel_length" value="0.200" />
        <xacro:property name="rear_wheel_radius" value="0.290" />

        <!-- Kinematics -->
        <xacro:property name="wheelbase"         value="1.212" />
        <xacro:property name="front_track_width" value="0.970" />
        <xacro:property name="rear_track_width"  value="0.938" />

        <!-- Front chassis dimensions -->
        <xacro:property name="bumper_x_size" value="0.490" />
        <xacro:property name="bumper_y_size" value="0.380" />
        <xacro:property name="bumper_z_size" value="0.360" />

        <!-- ======================================== Links ======================================== -->

        <!-- Base Footprint -->
        <link name="base_footprint"/>

        <!-- Base link -->
        <link name="base_link"/>

        <!-- Chassis -->
        <link name="chassis">

            <!-- Inertia -->
            <inertial>
                <mass value="160"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="20.43" ixy="0.584" ixz="-0.191" iyy="54.197" iyz="-0.2449" izz="72.2588"/>
            </inertial>

            <!-- Chassis -->
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="1.212 1.160 0.260"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="-0.6885 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.165 1.160 0.260"/>
                </geometry>
            </collision>
            <collision>
                <origin xyz="0.640 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.068 1.160 0.260"/>
                </geometry>
            </collision>
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="file://$(find erp42_racing_description)/meshes/erp42_racing_chassis.dae"  scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>

            <!-- Bumper -->
            <collision>
                <origin xyz="${wheelbase/2 + bumper_x_size/2 + 0.068} 0 0.05" rpy="0 0 0" />
                <geometry>
                    <box size="${bumper_x_size} ${bumper_y_size} ${bumper_z_size}"/>
                </geometry>
            </collision>
            <visual>
                <origin xyz="${wheelbase/2 + bumper_x_size/2 + 0.068} 0 0.05" rpy="0 0 0" />
                <geometry>
                    <mesh filename="file://$(find erp42_racing_description)/meshes/erp42_racing_bumper.dae"  scale="0.001 0.001 0.001"/>
                </geometry>
            </visual>

        </link>

        <!-- Steering assemblies -->
        <link name="front_left_steering_hub">

            <!-- Inertia -->
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
            </inertial>

        </link>

        <link name="front_right_steering_hub">

            <!-- Inertia -->
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001"/>
            </inertial>

        </link>

        <!-- Wheels -->
        <xacro:erp42_racing_front_wheel link_name="front_left_wheel" />
        <xacro:erp42_racing_front_wheel link_name="front_right_wheel"/>
        <xacro:erp42_racing_rear_wheel  link_name="rear_left_wheel"  />
        <xacro:erp42_racing_rear_wheel  link_name="rear_right_wheel" />

        <!-- ======================================== Joints ======================================== -->

        <!-- base_footprint to base_link -->
        <joint name="base_link_joint" type="fixed">
            <origin xyz="0 0 ${rear_wheel_radius}" rpy="0 0 0" />
            <parent link="base_footprint" />
            <child link="base_link" />
        </joint>

        <!-- base_link to chassis -->
        <joint name="chassis_joint" type="fixed">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <parent link="base_link" />
            <child link="chassis" />
        </joint>

        <!-- base_link to front_left_steering_hub -->
        <joint name="front_left_steering_hub_joint" type="revolute">
            <origin xyz="${wheelbase/2} ${front_track_width/2} -0.01" rpy="0 0 0" />
            <parent link="base_link"/>
            <child link="front_left_steering_hub"/>
            <axis xyz="0 0 1"/>
            <limit lower="-0.698132" upper="0.698132" effort="100" velocity="100"/>
            <dynamics damping="0.1" friction="0.1"/>
        </joint>

        <!-- base_link to front_right_steering_hub -->
        <joint name="front_right_steering_hub_joint" type="revolute">
            <origin xyz="${wheelbase/2} ${-front_track_width/2} -0.01" rpy="0 0 0" />
            <parent link="base_link"/>
            <child link="front_right_steering_hub"/>
            <axis xyz="0 0 1"/>
            <limit lower="-0.698132" upper="0.698132" effort="100" velocity="100"/>
            <dynamics damping="0.1" friction="0.1"/>
        </joint>

        <!-- front_left_steering_hub to front_right_wheel -->
        <joint name="front_left_wheel_joint" type="continuous">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <parent link="front_left_steering_hub"/>
            <child link="front_left_wheel"/>
            <axis xyz="0 1 0"/>
        </joint>

        <!-- front_right_steering_hub to front_right_wheel -->
        <joint name="front_right_wheel_joint" type="continuous">
            <origin xyz="0 0 0" rpy="${PI} 0 0" />
            <parent link="front_right_steering_hub"/>
            <child link="front_right_wheel"/>
            <axis xyz="0 -1 0"/>
        </joint>

        <!-- base_link to rear_left_wheel -->
        <joint name="rear_left_wheel_joint" type="continuous">
            <origin xyz="${-wheelbase/2} ${rear_track_width/2} 0" rpy="0 0 0" />
            <parent link="base_link"/>
            <child link="rear_left_wheel"/>
            <axis xyz="0 1 0"/>
        </joint>

        <!-- base_link to rear_right_wheel -->
        <joint name="rear_right_wheel_joint" type="continuous">
            <origin xyz="${-wheelbase/2} ${-rear_track_width/2} 0" rpy="${PI} 0 0" />
            <parent link="base_link"/>
            <child link="rear_right_wheel"/>
            <axis xyz="0 -1 0"/>
        </joint>

    </xacro:macro>
</robot>